[build]
  command = "bun run build" # atau tsc tergantung setup kamu
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["server.ts", "config/**", "routes/**", "middleware/**", ".env"]
